
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EED
 */
public class form_login extends javax.swing.JFrame {

    /**
     * Creates new form form_login
     */
    Koneksi k;
    Connection con;
    Petugas data;
    PetugasDao dao;

    public form_login() {
        initComponents();
        k = new Koneksi();
        try {
            con = k.getConnection();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        data = new Petugas();
        dao = new PetugasDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        tombollogin = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        tombolexit = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        id.setBorder(null);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 308, 380, 41));

        tombollogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol login.png"))); // NOI18N
        tombollogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolloginMouseExited(evt);
            }
        });
        getContentPane().add(tombollogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 467, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 382, 380, 41));

        jPanel1.setBackground(new java.awt.Color(255, 218, 215));

        tombolexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol keluar_1.png"))); // NOI18N
        tombolexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolexitMouseExited(evt);
            }
        });
        jPanel1.add(tombolexit);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 290, 90));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Login.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getId() {
        return id;
    }

    public JPasswordField getPassword() {
        return password;
    }

    private void clear() {
        id.setText("");
        password.setText("");
        id.setEnabled(true);
        password.setEnabled(true);
    }

    public String getLogin() throws SQLException{
        String sql = "select id from login limit 1";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        if(rs.next()){
            return rs.getString(1);
        }
        return "admin";
    }
    
    public void Login() throws SQLException {
        String kode = id.getText();
        if (id.getText().equals("admin") && password.getText().equals("admin")) {
            new form_home().setVisible(true);
            this.dispose();;
        }else{  
            try {
                data = dao.getPetugas(kode);
                if (data != null) {

                    if (id.getText().equals(data.getId()) && password.getText().equals(data.getPassword())) {
                        String sql = "insert into login values(?,?)";
                        PreparedStatement ps = con.prepareStatement(sql);
                        ps.setString(1, id.getText());
                        ps.setString(2, password.getText());
                        ps.executeUpdate();
                        new form_home().setVisible(true);
                        this.dispose();
                    } else {
                    JOptionPane.showMessageDialog(null, "Id atau Password salah");
                }
                } else {
                    JOptionPane.showMessageDialog(null, "Id atau Password salah");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }


    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void tombolloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol login 2.png"));
        tombollogin.setIcon(pg);
    }//GEN-LAST:event_tombolloginMouseEntered

    private void tombolloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol login.png"));
        tombollogin.setIcon(pg);
    }//GEN-LAST:event_tombolloginMouseExited

    private void tombolloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMouseClicked
        try {
            Login();
        } catch (SQLException ex) {
            Logger.getLogger(form_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolloginMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void tombolexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolexitMouseEntered
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol keluar 2_1.png"));
        tombolexit.setIcon(pg);
    }//GEN-LAST:event_tombolexitMouseEntered

    private void tombolexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolexitMouseExited
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol keluar_1.png"));
        tombolexit.setIcon(pg);
    }//GEN-LAST:event_tombolexitMouseExited

    private void tombolexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolexitMouseClicked
        this.dispose();
    }//GEN-LAST:event_tombolexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel tombolexit;
    private javax.swing.JLabel tombollogin;
    // End of variables declaration//GEN-END:variables
}
