
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EED
 */
public class form_anggota extends javax.swing.JFrame {

    /**
     * Creates new form form_anggota
     */
    AnggotaController controller;
    
    public form_anggota() {
        initComponents();
        controller = new AnggotaController(this);
        controller.isiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        nama_txt = new javax.swing.JTextField();
        ttl_txt = new javax.swing.JTextField();
        idanggota_txt = new javax.swing.JTextField();
        alamat_txt = new javax.swing.JTextField();
        nik_txt = new javax.swing.JTextField();
        nohp_txt = new javax.swing.JTextField();
        tombolcari = new javax.swing.JLabel();
        tombolproses = new javax.swing.JLabel();
        tombolhapus = new javax.swing.JLabel();
        tombolberanda = new javax.swing.JLabel();
        rb_pr = new javax.swing.JRadioButton();
        rb_lk = new javax.swing.JRadioButton();
        tombolupdate = new javax.swing.JLabel();
        cari_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nama_txt.setBorder(null);
        nama_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_txtActionPerformed(evt);
            }
        });
        getContentPane().add(nama_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 281, 255, 23));

        ttl_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ttl_txt.setBorder(null);
        getContentPane().add(ttl_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 321, 255, 23));

        idanggota_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        idanggota_txt.setBorder(null);
        getContentPane().add(idanggota_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 535, 255, 23));

        alamat_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        alamat_txt.setBorder(null);
        alamat_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat_txtActionPerformed(evt);
            }
        });
        getContentPane().add(alamat_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 444, 255, 23));

        nik_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nik_txt.setBorder(null);
        getContentPane().add(nik_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 403, 255, 23));

        nohp_txt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nohp_txt.setBorder(null);
        nohp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohp_txtActionPerformed(evt);
            }
        });
        getContentPane().add(nohp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 487, 255, 23));

        tombolcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol cari.png"))); // NOI18N
        tombolcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolcariMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolcariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolcariMouseExited(evt);
            }
        });
        getContentPane().add(tombolcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 157, -1, -1));

        tombolproses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol proses.png"))); // NOI18N
        tombolproses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolprosesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolprosesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolprosesMouseExited(evt);
            }
        });
        getContentPane().add(tombolproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 583, -1, -1));

        tombolhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol hapus.png"))); // NOI18N
        tombolhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolhapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolhapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolhapusMouseExited(evt);
            }
        });
        getContentPane().add(tombolhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 652, -1, -1));

        tombolberanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol beranda.png"))); // NOI18N
        tombolberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolberandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolberandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolberandaMouseExited(evt);
            }
        });
        getContentPane().add(tombolberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 652, -1, -1));

        rb_pr.setBackground(new java.awt.Color(198, 215, 220));
        jk.add(rb_pr);
        rb_pr.setBorder(null);
        rb_pr.setMargin(new java.awt.Insets(2, 2, 3, 2));
        rb_pr.setMaximumSize(new java.awt.Dimension(25, 25));
        rb_pr.setPreferredSize(new java.awt.Dimension(25, 25));
        rb_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_prActionPerformed(evt);
            }
        });
        getContentPane().add(rb_pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 363, 20, -1));

        rb_lk.setBackground(new java.awt.Color(198, 215, 220));
        jk.add(rb_lk);
        rb_lk.setBorder(null);
        rb_lk.setMargin(new java.awt.Insets(2, 2, 3, 2));
        rb_lk.setMaximumSize(new java.awt.Dimension(25, 25));
        rb_lk.setPreferredSize(new java.awt.Dimension(25, 25));
        rb_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_lkActionPerformed(evt);
            }
        });
        getContentPane().add(rb_lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 363, -1, -1));
        getContentPane().add(tombolupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, -1, -1));

        cari_txt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cari_txt.setBorder(null);
        cari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_txtActionPerformed(evt);
            }
        });
        getContentPane().add(cari_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 165, 130, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabelAnggota.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Anggota", "Nama", "Tempat, tanggal lahir", "Jenis Kelamin", "Alamat", "NIK", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelAnggota.setRowHeight(30);
        tabelAnggota.setRowMargin(2);
        tabelAnggota.setSelectionBackground(new java.awt.Color(229, 171, 171));
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAnggota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 770, 480));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Form Anggota.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getAlamat_txt() {
        return alamat_txt;
    }

    public ButtonGroup getJk() {
        return jk;
    }

    public JTextField getNama_txt() {
        return nama_txt;
    }

    public JTextField getNik_txt() {
        return nik_txt;
    }

    public JTextField getNohp_txt() {
        return nohp_txt;
    }

    public JRadioButton getRb_lk() {
        return rb_lk;
    }

    public JRadioButton getRb_pr() {
        return rb_pr;
    }

    public JTextField getTtl_txt() {
        return ttl_txt;
    }

    public JTextField getIdanggota_txt() {
        return idanggota_txt;
    }

    public JTable getTabelAnggota() {
        return tabelAnggota;
    }

    public JTextField getCari_txt() {
        return cari_txt;
    }

    
    private void nohp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohp_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohp_txtActionPerformed

    private void tombolhapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolhapusMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol hapus 2.png"));
        tombolhapus.setIcon(pg);
    }//GEN-LAST:event_tombolhapusMouseEntered

    private void tombolhapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolhapusMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol hapus.png"));
        tombolhapus.setIcon(pg);
    }//GEN-LAST:event_tombolhapusMouseExited

    private void tombolberandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol beranda 2.png"));
        tombolberanda.setIcon(pg);
    }//GEN-LAST:event_tombolberandaMouseEntered

    private void tombolberandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol beranda.png"));
        tombolberanda.setIcon(pg);
    }//GEN-LAST:event_tombolberandaMouseExited

    private void nama_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_txtActionPerformed

    private void tombolberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseClicked
        // TODO add your handling code here:
        new form_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolberandaMouseClicked

    private void rb_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_prActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_prActionPerformed

    private void rb_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_lkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_lkActionPerformed

    private void tombolhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolhapusMouseClicked
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data?", null, JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION) {
            controller.delete();
            controller.isiTable();
            controller.clear();
        }
    }//GEN-LAST:event_tombolhapusMouseClicked

    private void alamat_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat_txtActionPerformed

    private void cari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_txtActionPerformed

    private void tombolprosesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolprosesMouseClicked
        controller.insert();
        controller.clear();
        controller.isiTable();
    }//GEN-LAST:event_tombolprosesMouseClicked

    private void tombolprosesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolprosesMouseEntered
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol proses 2.png"));
        tombolproses.setIcon(pg);
    }//GEN-LAST:event_tombolprosesMouseEntered

    private void tombolprosesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolprosesMouseExited
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol proses.png"));
        tombolproses.setIcon(pg);
    }//GEN-LAST:event_tombolprosesMouseExited

    private void tombolcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolcariMouseClicked
        // TODO add your handling code here:
        controller.search();
        cari_txt.setText("");
    }//GEN-LAST:event_tombolcariMouseClicked

    private void tombolcariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolcariMouseEntered
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol cari 2.png"));
        tombolcari.setIcon(pg);
    }//GEN-LAST:event_tombolcariMouseEntered

    private void tombolcariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolcariMouseExited
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol cari.png"));
        tombolcari.setIcon(pg);
    }//GEN-LAST:event_tombolcariMouseExited

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        controller.tabelklik();
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_txt;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cari_txt;
    private javax.swing.JTextField idanggota_txt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JTextField nama_txt;
    private javax.swing.JTextField nik_txt;
    private javax.swing.JTextField nohp_txt;
    private javax.swing.JRadioButton rb_lk;
    private javax.swing.JRadioButton rb_pr;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JLabel tombolberanda;
    private javax.swing.JLabel tombolcari;
    private javax.swing.JLabel tombolhapus;
    private javax.swing.JLabel tombolproses;
    private javax.swing.JLabel tombolupdate;
    private javax.swing.JTextField ttl_txt;
    // End of variables declaration//GEN-END:variables
}
