
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EED
 */
public class form_home extends javax.swing.JFrame {

    /**
     * Creates new form from_home
     */
    Koneksi k;
    Connection con;
    Petugas data;
    PetugasDao dao;
    form_login login;

    public form_home() {
        initComponents();
        k = new Koneksi();
        try {
            con = k.getConnection();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        data = new Petugas();
        dao = new PetugasDao();
        login = new form_login();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolanggota = new javax.swing.JLabel();
        tombolpeminjaman = new javax.swing.JLabel();
        tombolbuku = new javax.swing.JLabel();
        tombollaporan = new javax.swing.JLabel();
        tombolkeluar = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolanggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Anggota (1).png"))); // NOI18N
        tombolanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolanggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolanggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolanggotaMouseExited(evt);
            }
        });
        getContentPane().add(tombolanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 210, -1, -1));

        tombolpeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/form peminjaman.png"))); // NOI18N
        tombolpeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolpeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolpeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolpeminjamanMouseExited(evt);
            }
        });
        getContentPane().add(tombolpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 210, -1, -1));

        tombolbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Buku.png"))); // NOI18N
        tombolbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolbukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolbukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolbukuMouseExited(evt);
            }
        });
        getContentPane().add(tombolbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 210, -1, -1));

        tombollaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan.png"))); // NOI18N
        tombollaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombollaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombollaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombollaporanMouseExited(evt);
            }
        });
        getContentPane().add(tombollaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 210, -1, -1));

        tombolkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol keluar.png"))); // NOI18N
        tombolkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolkeluarMouseExited(evt);
            }
        });
        getContentPane().add(tombolkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 210, -1, -1));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 665, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Home.png"))); // NOI18N
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void delete() throws SQLException {
        ResultSet rs = k.getQuery(con, "SELECT * FROM login");
        while (rs.next()) {
            String sql = "delete from login where id=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, rs.getString(1));
            ps.executeUpdate();
        }
    }
  
    public void cek() throws SQLException{
        if(login.getLogin()!="admin"){
            user.hide();
        }
    }

    private void tombolpeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolpeminjamanMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/form peminjaman 2.png"));
        tombolpeminjaman.setIcon(pg);
    }//GEN-LAST:event_tombolpeminjamanMouseEntered

    private void tombolpeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolpeminjamanMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/form peminjaman.png"));
        tombolpeminjaman.setIcon(pg);
    }//GEN-LAST:event_tombolpeminjamanMouseExited

    private void tombolbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbukuMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/Buku 2.png"));
        tombolbuku.setIcon(pg);
    }//GEN-LAST:event_tombolbukuMouseEntered

    private void tombolbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbukuMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/Buku.png"));
        tombolbuku.setIcon(pg);
    }//GEN-LAST:event_tombolbukuMouseExited

    private void tombolanggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolanggotaMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/Anggota 2.png"));
        tombolanggota.setIcon(pg);
    }//GEN-LAST:event_tombolanggotaMouseEntered

    private void tombolanggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolanggotaMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/Anggota (1).png"));
        tombolanggota.setIcon(pg);
    }//GEN-LAST:event_tombolanggotaMouseExited

    private void tombollaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombollaporanMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan 2.png"));
        tombollaporan.setIcon(pg);
    }//GEN-LAST:event_tombollaporanMouseEntered

    private void tombollaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombollaporanMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan.png"));
        tombollaporan.setIcon(pg);
    }//GEN-LAST:event_tombollaporanMouseExited

    private void tombolkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkeluarMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol keluar 2.png"));
        tombolkeluar.setIcon(pg);
    }//GEN-LAST:event_tombolkeluarMouseEntered

    private void tombolkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkeluarMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol keluar.png"));
        tombolkeluar.setIcon(pg);
    }//GEN-LAST:event_tombolkeluarMouseExited

    private void tombolkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkeluarMouseClicked
        try {
            // TODO add your handling code here:
            delete();
        } catch (SQLException ex) {
            Logger.getLogger(form_home.class.getName()).log(Level.SEVERE, null, ex);
        }
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?", null, JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION) {
            new form_login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tombolkeluarMouseClicked

    private void tombolbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbukuMouseClicked
        // TODO add your handling code here:
        new form_buku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolbukuMouseClicked

    private void tombolanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolanggotaMouseClicked
        // TODO add your handling code here:
        new form_anggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolanggotaMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        
        new form_petugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void tombolpeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolpeminjamanMouseClicked
        try {
            new form_peminjaman().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(form_home.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_tombolpeminjamanMouseClicked

    private void tombollaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombollaporanMouseClicked
        new laporananggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombollaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    private javax.swing.JLabel tombolanggota;
    private javax.swing.JLabel tombolbuku;
    private javax.swing.JLabel tombolkeluar;
    private javax.swing.JLabel tombollaporan;
    private javax.swing.JLabel tombolpeminjaman;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private Object form_login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
