
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EED
 */
public class laporanpeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    Koneksi k;
    Connection con;
    
    public laporanpeminjaman() {
        initComponents();
        k = new Koneksi();
        con = k.getConnection();
        isiTable();
    }

    public void isiTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabelPeminjaman.getModel();
            model.setRowCount(0);
            ResultSet rs = k.getQuery(con, "SELECT * FROM peminjaman");
            while (rs.next()) {
                Object data[] = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10)
                };
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AnggotaController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        tombolberanda = new javax.swing.JLabel();
        buku = new javax.swing.JLabel();
        peminjaman = new javax.swing.JLabel();
        anggota = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPeminjaman.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pinjam", "Id Anggota", "Id Buku", "Id Petugas", "Tanggal Pinjam", "Tanggal Kembali", "Tanggal dikembalikan", "Status", "Terlambat", "Denda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPeminjaman.setRowHeight(30);
        tabelPeminjaman.setRowMargin(2);
        tabelPeminjaman.setSelectionBackground(new java.awt.Color(229, 171, 171));
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1260, 500));

        tombolberanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tombol beranda.png"))); // NOI18N
        tombolberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolberandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolberandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolberandaMouseExited(evt);
            }
        });
        getContentPane().add(tombolberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 658, -1, -1));

        buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan buku.png"))); // NOI18N
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bukuMouseExited(evt);
            }
        });
        getContentPane().add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 100, -1, -1));

        peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan peminjaman 2.png"))); // NOI18N
        getContentPane().add(peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan anggota.png"))); // NOI18N
        anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anggotaMouseExited(evt);
            }
        });
        getContentPane().add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Laporan_2.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        //controller.tabelklik();
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void tombolberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseClicked
        // TODO add your handling code here:
        new form_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolberandaMouseClicked

    private void tombolberandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseEntered
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol beranda 2.png"));
        tombolberanda.setIcon(pg);
    }//GEN-LAST:event_tombolberandaMouseEntered

    private void tombolberandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMouseExited
        // TODO add your handling code here:
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/tombol beranda.png"));
        tombolberanda.setIcon(pg);
    }//GEN-LAST:event_tombolberandaMouseExited

    private void anggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseEntered
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan anggota 2.png"));
        anggota.setIcon(pg);
    }//GEN-LAST:event_anggotaMouseEntered

    private void anggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseExited
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan anggota.png"));
        anggota.setIcon(pg);
    }//GEN-LAST:event_anggotaMouseExited

    private void bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseEntered
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan buku 2.png"));
        buku.setIcon(pg);
    }//GEN-LAST:event_bukuMouseEntered

    private void bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseExited
        ImageIcon pg = new ImageIcon(getClass().getResource("gambar/laporan buku.png"));
        buku.setIcon(pg);
    }//GEN-LAST:event_bukuMouseExited

    private void anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseClicked
        new laporananggota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anggotaMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        new laporanbuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanpeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anggota;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel buku;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JTable tabelPeminjaman;
    private javax.swing.JLabel tombolberanda;
    // End of variables declaration//GEN-END:variables
}
